name: Deploy Sanity
on:
  push:
    branches: [main]
jobs:
  sanity-deploy:
    runs-on: ubuntu-latest
    name: Deploy Sanity
    environment: prod
    defaults:
      run:
        working-directory: ./studio
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Packages
        run: pnpm install

      - name: Deploy Sanity
        run: pnpm deploy
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}
          SANITY_STUDIO_PROJECT_ID: ${{ secrets.SANITY_STUDIO_PROJECT_ID }}
          SANITY_STUDIO_DATASET: ${{ secrets.SANITY_STUDIO_DATASET }}
          SANITY_STUDIO_PREVIEW_URL: ${{ secrets.SANITY_STUDIO_PREVIEW_URL }}
          SANITY_STUDIO_APP_BASE_URL: ${{ secrets.SANITY_STUDIO_APP_BASE_URL }}
          SANITY_STUDIO_APP_API_TOKEN: ${{ secrets.SANITY_STUDIO_APP_API_TOKEN }}
          SANITY_STUDIO_SUPABASE_URL: ${{ secrets.SANITY_STUDIO_SUPABASE_URL }}
          SANITY_STUDIO_SUPABASE_KEY: ${{ secrets.SANITY_STUDIO_SUPABASE_KEY }}
          SANITY_STUDIO_SLACK_HOOK: ${{ secrets.SANITY_STUDIO_SLACK_HOOK }}
 
